// state.js — 여러 모듈이 값을 바꾸는 공유 상태
// 읽기만 하는 값은 각 모듈이 그대로 export 한다 (ES 모듈 라이브 바인딩).
export const S = {
  booted: false,
  worldSeed: 0,
  terrain: 0,
  urlSeed: null,
  slot: 1,
  worldDirty: false,
  saveTimer: 0,
  timeOfDay: 0.30,
  moonDay: 0,
  bar: null,
  barAlt: null,
  barPage: 1,
  flySpeed: 1,
  earned: {},
  placedKinds: {},
  lampsPlaced: 0,
  torchesPlaced: 0,
  playSeconds: 0,
  tut: 0,
  muted: false,
  relightQueued: false,
  shapeMode: 0, // 0 전체 · 1 반블록 · 2 계단
  bobPhase: 0,
  bobAmount: 0,
  stepPhase: 0,
  loadedFromSave: false,
  placeCooldown: 0,
  savedPos: null,
  savedYaw: 0,
  savedPitch: 0,
  lastRTap: -1e9, // R 오폭으로 세계가 날아가지 않도록
  loopPaused: false, // 테스트에서 시뮬레이션을 멈춰 세울 때만 쓴다
  weatherTimer: 40 + Math.random() * 60,
  mmTimer: 0,
  toastTimer: 0,
  selected: 0,
  active: false,
  started: false,
  lockMode: true,
  uiOpen: false,
  keys: Object.create(null),
  weather: 0,
  sneaking: false,
  sprintTap: false, // W 더블탭으로 걸린 달리기
  sprintingNow: false,
  lastFwdTap: 0,
  lastSpaceTap: 0,
  lastPlaceCell: -1,
  hudHidden: false,
  autoPerf: true,
  perfDrop: 0,
  farWanted: 0,
  wantShot: false,
  showPerf: false,
  spawnPoint: null,
  thirdPerson: 0,
  photoMode: false,
  swing: 0,
  heldKey: -1,
  ghostKey: -1,
  sneakEye: 0, // 웅크릴 때 눈높이가 부드럽게 내려간다
  fovNow: 0, // 달릴 때 시야각 킥
  hudTimer: 0,
  fpsAccum: 0,
  fpsFrames: 0,
  waterTimer: 0,
  achTimer: 0,
  lavaTimer: 0,
  caveTimer: 6,
  moodTimer: 40,
  oxygen: 1,
  mmZoom: 1,
  contour: true,
  liquidTimer: 0,
  freezeTimer: 0,
  torchFxTimer: 0,
  wasInLavaFeet: false,   // 용암에 발을 담그는 순간 치익 소리를 내려고
  wasUnderwater: false,
  wasInLava: false,
  wasOnGround: true,
  creaturePhase: 0,
  mmUnder: false,
  weatherPhase: 0,
  weatherMix: 0,
  rainTimer: 0,
  snowTimer: 0,
  stormTimer: 8,
  flash: 0,
  cricketTimer: 0,
  saveWarned: false,
  dragging: false,
  dragBtn: -1,
  dragDist: 0,
  dragStart: 0,
  touchBreak: false,
  stickId: null,
  lookId: null,
  breaking: { on: false, x: 0, y: 0, z: 0, t: 0, need: 1, stage: -1, sw: 0 },
  audioCtx: null,
  masterGain: null,
  muffle: null,
  ambient: null,
  history: [],
  batch: null,
  selA: null,
  selB: null,
  clip: null,
  marks: [],
  recent: [],
  binds: { fly: "KeyF", shape: "KeyG", pick: "KeyQ", help: "KeyH" },
  future: [],
  stick: { x: 0, z: 0 },
  mouseDown: [false, false, false],
};
